/**
 * Returns reactive page title. Cukup "title" saja, tanpa key embel-embel.
 * Nilai diambil dari peta lokal (bukan i18n key).
 */
const TITLES: Record<string, Record<string, string>> = {
  en: {
    dashboard: 'Dashboard',
    settings: 'Settings',
    management: 'Management',
    users: 'Users',
    roles: 'Roles',
    employee: 'Employee',
    employeeDatabase: 'Employee',
    employeeContracts: 'Employee Contracts',
    employeeDocuments: 'Employee Documents',
    promotion: 'Promotion',
    retired: 'Retired',
    mutation: 'Mutation',
    myAttendance: 'My Attendance',
    teamAttendance: 'Team Attendance',
    shiftSchedule: 'Shift Schedule',
    taOvertime: 'Overtime',
    attendanceReports: 'Attendance Reports',
    myLeave: 'My Leave',
    leaveRequest: 'Leave Request',
    businessTrip: 'Business Trip',
    leaveReports: 'Leave Reports',
    myKpi: 'My KPI',
    assignKpi: 'Assign KPI',
    selfAssessment: 'Self-Assessment',
    teamReview: 'Team Review',
    calibration: 'Calibration',
    pip: 'PIP',
    nineGridBox: '9-Grid Box',
    performancePromotion: 'Promotion',
    performanceMutation: 'Mutation',
    payslip: 'Payslip',
    benefits: 'Benefits',
    bonusIncentive: 'Bonus & Incentive',
    compAdjustment: 'Comp Adjustment',
    payrollRun: 'Payroll Run',
    requisitions: 'Requisitions',
    jobOpenings: 'Job Openings',
    talentCandidates: 'Candidate',
    talentRecruitment: 'Recruitment',
    headcountForecast: 'Headcount Forecast',
    demandTracker: 'Demand Tracker',
    resourceAllocation: 'Resource Allocation',
    keyRoles: 'Key Roles',
    successorPool: 'Successor Pool',
    myLearning: 'My Learning',
    courseCatalog: 'Course Catalog',
    certifications: 'Certifications',
    training: 'Training',
    burnoutIndicator: 'Burnout Indicator',
    attritionForecast: 'Attrition Forecast',
    trainingSuggestions: 'Training Suggestions',
    submitRequest: 'Submit Request',
    myTickets: 'My Tickets',
    serviceConsole: 'Service Console',
    myTasks: 'My Tasks',
    assignTask: 'Assign Task',
    evidenceReview: 'Evidence Review',
    attendance: 'Attendance',
    cuti: 'Leave',
    leave: 'Leave',
    overtime: 'Overtime',
    recruitment: 'Recruitment',
    recruitmentFunnel: 'Recruitment Funnel',
    candidates: 'Candidates',
    positions: 'Positions',
    company: 'Company',
    department: 'Department',
    divisi: 'Division',
    positionLevel: 'Position Level',
    location: 'Location',
    organization: 'Organization',
    approvalHierarchy: 'Approval Hierarchy',
    learningHub: 'Learning Hub',
    kpi: 'KPI',
    shifts: 'Shifts',
    workforceReports: 'Workforce Reports',
    announcements: 'Announcements',
    wfm: 'Workforce Management',
    wfmShiftSwap: 'Shift Swap',
    wfmAvailability: 'Availability',
    wfmHolidays: 'Holidays',
    wfmCompliance: 'Compliance',
    wfmOnboarding: 'Onboarding / Offboarding',
    wfmLeaveCalendar: 'Leave Calendar',
    wfmLaborCost: 'Labor Cost',
  },
  id: {
    dashboard: 'Dashboard',
    settings: 'Pengaturan',
    management: 'Management',
    users: 'Pengguna',
    roles: 'Roles',
    employee: 'Karyawan',
    employeeDatabase: 'Karyawan',
    employeeContracts: 'Kontrak Karyawan',
    employeeDocuments: 'Dokumen Karyawan',
    promotion: 'Promosi',
    retired: 'Pensiun',
    mutation: 'Mutasi',
    myAttendance: 'My Attendance',
    teamAttendance: 'Team Attendance',
    shiftSchedule: 'Shift Schedule',
    taOvertime: 'Overtime',
    attendanceReports: 'Attendance Reports',
    myLeave: 'My Leave',
    leaveRequest: 'Leave Request',
    businessTrip: 'Business Trip',
    leaveReports: 'Leave Reports',
    myKpi: 'My KPI',
    assignKpi: 'Assign KPI',
    selfAssessment: 'Self-Assessment',
    teamReview: 'Team Review',
    calibration: 'Calibration',
    pip: 'PIP',
    nineGridBox: '9-Grid Box',
    performancePromotion: 'Promotion',
    performanceMutation: 'Mutation',
    payslip: 'Payslip',
    benefits: 'Benefits',
    bonusIncentive: 'Bonus & Incentive',
    compAdjustment: 'Comp Adjustment',
    payrollRun: 'Payroll Run',
    requisitions: 'Requisitions',
    jobOpenings: 'Job Openings',
    talentCandidates: 'Candidate',
    talentRecruitment: 'Recruitment',
    headcountForecast: 'Headcount Forecast',
    demandTracker: 'Demand Tracker',
    resourceAllocation: 'Resource Allocation',
    keyRoles: 'Key Roles',
    successorPool: 'Successor Pool',
    myLearning: 'My Learning',
    courseCatalog: 'Course Catalog',
    certifications: 'Certifications',
    training: 'Training',
    burnoutIndicator: 'Burnout Indicator',
    attritionForecast: 'Attrition Forecast',
    trainingSuggestions: 'Training Suggestions',
    submitRequest: 'Submit Request',
    myTickets: 'My Tickets',
    serviceConsole: 'Service Console',
    myTasks: 'My Tasks',
    assignTask: 'Assign Task',
    evidenceReview: 'Evidence Review',
    attendance: 'Kehadiran',
    cuti: 'Cuti',
    leave: 'Cuti',
    overtime: 'Lembur',
    recruitment: 'Rekrutmen',
    recruitmentFunnel: 'Recruitment Funnel',
    candidates: 'Kandidat',
    positions: 'Posisi',
    company: 'Perusahaan',
    department: 'Departemen',
    divisi: 'Divisi',
    positionLevel: 'Jenjang Jabatan',
    location: 'Lokasi',
    organization: 'Organisasi',
    approvalHierarchy: 'Hirarki Approval',
    learningHub: 'Learning Hub',
    kpi: 'KPI',
    shifts: 'Shift & Jadwal',
    workforceReports: 'Laporan Tenaga Kerja',
    announcements: 'Pengumuman',
    wfm: 'Workforce Management',
    wfmShiftSwap: 'Tukar Shift',
    wfmAvailability: 'Ketersediaan',
    wfmHolidays: 'Hari Libur',
    wfmCompliance: 'Compliance Jadwal',
    wfmOnboarding: 'Onboarding / Offboarding',
    wfmLeaveCalendar: 'Kalender Cuti',
    wfmLaborCost: 'Biaya Tenaga Kerja',
  },
}

export function usePageTitle(module?: string) {
  const { locale } = useI18n()
  const state = useState<string>('pageTitleModule', () => 'dashboard')
  if (module !== undefined) state.value = module
  const title = computed(() => {
    const loc = locale.value || 'en'
    const mod = state.value || 'dashboard'
    return TITLES[loc]?.[mod] ?? TITLES[loc]?.dashboard ?? 'Dashboard'
  })
  return { title }
}
